#!/usr/bin/env npx tsx
/**
 * Idempotent local RC for trade-details + decision monitor.
 * One database, migrations, 100M session, tracing, collector, Next on 3210.
 * Never touches production.
 */
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const PORT = Number(process.env.SHADOW_LOCAL_PORT ?? 3210);
const DB = process.env.DATABASE_URL ?? "pglite:.data/pglite-trade-details-rc";
const HOST = "127.0.0.1";

function log(msg: string) {
  console.log(`[local-rc] ${msg}`);
}

function killPort(port: number) {
  const r = spawnSync("lsof", ["-tiTCP:" + port, "-sTCP:LISTEN"], { encoding: "utf8" });
  const pids = (r.stdout || "").trim().split(/\s+/).filter(Boolean);
  for (const pid of pids) {
    log(`stopping pid ${pid} on :${port}`);
    try {
      process.kill(Number(pid), "SIGTERM");
    } catch {
      /* ignore */
    }
  }
}

// Ensure data dir
const dataDir = path.join(root, ".data");
if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true });

// Write env for Next (escaped $ for dotenv)
function genHash(pw: string): string {
  const r = spawnSync("node", ["scripts/generate-password-hash.mjs", pw], {
    cwd: root,
    encoding: "utf8"
  });
  return (r.stdout || "").trim().split("\n")[0]!;
}
const adminHash = genHash("LocalRC4130!");
const viewerHash = genHash("viewer123");
const esc = (s: string) => s.replace(/\$/g, "\\$");
const envPath = path.join(root, ".env.development.local");
writeFileSync(
  envPath,
  [
    "# Generated by start-local-trade-rc.mts — local only, gitignored",
    "ADMIN_USERNAME=otc-iman",
    `ADMIN_PASSWORD_HASH=${esc(adminHash)}`,
    "VIEWER_USERNAME=usser",
    `VIEWER_PASSWORD_HASH=${esc(viewerHash)}`,
    "AUTH_TOKEN_SECRET=local-rc-trade-details-secret-32chars-min",
    `DATABASE_URL=${DB}`,
    "SHADOW_COLLECTOR_ENABLED=true",
    "SHADOW_DECISION_TRACE=true",
    "SHADOW_RELEASE_BOOTSTRAP=false",
    "NODE_ENV=development"
  ].join("\n") + "\n"
);
log(`wrote ${envPath}`);
log(`DATABASE_URL=${DB}`);

killPort(PORT);
// brief wait
spawnSync("sleep", ["1"]);

// migrate + seed via same DATABASE_URL
const env = {
  ...process.env,
  DATABASE_URL: DB,
  SHADOW_DECISION_TRACE: "true",
  SHADOW_COLLECTOR_ENABLED: "true",
  NODE_ENV: "development"
};

log("migrations…");
let r = spawnSync("npx", ["--yes", "tsx", "src/db/migrate.ts"], {
  cwd: root,
  env,
  encoding: "utf8"
});
if (r.status !== 0) {
  console.error(r.stdout, r.stderr);
  process.exit(1);
}
log((r.stdout || "").trim().split("\n").slice(-3).join(" | "));

log("seed 100M paper session…");
r = spawnSync("npx", ["--yes", "tsx", "scripts/seed-local-paper-100m.mts"], {
  cwd: root,
  env,
  encoding: "utf8"
});
console.log(r.stdout || r.stderr);
if (r.status !== 0) process.exit(1);

log(`starting next on http://${HOST}:${PORT} …`);
const child: ChildProcess = spawn(
  "pnpm",
  ["exec", "next", "dev", "--hostname", HOST, "--port", String(PORT)],
  {
    cwd: root,
    env: {
      ...env,
      // Auth hashes come only from .env.development.local (avoid $ expansion corruption).
      PORT: String(PORT)
    },
    stdio: "inherit"
  }
);

const shutdown = () => {
  log("shutting down…");
  child.kill("SIGTERM");
  process.exit(0);
};
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

child.on("exit", (code) => {
  log(`next exited ${code}`);
  process.exit(code ?? 0);
});
